### ISSUE TITLE
Certificate and Private Key Mismatch

### ISSUE THREAD

**Issue by counterbeing** [paybyphone/terraform-provider-acme#1]
Hi there!

I've just been trying out this plugin as I've been looking for a way to automate applying "Lets Encrypt" certificates to an AWS CloudFront resource. Thing seemed to be going well, and I was getting a cert from the ACME provider, but then I try to upload it to AWS

```
resource "aws_iam_server_certificate" "some_cert" {
  name = "some_cert"
  certificate_body = "${acme_certificate.certificate.certificate_pem}"
  private_key = "${tls_private_key.private_key.private_key_pem}"
}
```

At this point amazon informed me that there was a mismatched. I created a couple of outlets in terraform to get a copy of the cert and key, and double confirmed the cert and key don't match using `openssl`.

I'm not sure if it's a problem with my setup, or maybe there's something going on in the plugin.

My setup, aside from some naming, is pretty much the same setup as your first example. If there's a better place to put this, please let me know.

Thanks!

**Comment by vancluever** [comment]
Hey @counterbeing, can you paste your full config for me? Just want to make sure, but if you are working off my example in the README, you are using the `private_key` from the registration instead of the private key from the certificate. The field you want is `acme_certificate.certificate.private_key_pem`.

Thanks!

**Comment by vancluever** [comment]
PS I merged in your doc correction - thanks! :)

**Comment by counterbeing** [comment]
You nailed the issue. For anyone that makes the same mistake as me, the private key for the cert is not the `tls_private_key` resource you generate (or pass in if you make one manually). Instead you want to use a private key that's provided by the `acme_certificate` resource itself. Here's how I'm now uploading a cert to amazon:

```
resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "reg" {
  server_url      = "https://acme-v01.api.letsencrypt.org/directory"
  account_key_pem = "${tls_private_key.private_key.private_key_pem}"
  email_address   = "me@example.com"
}

resource "acme_certificate" "certificate" {
  server_url                = "https://acme-v01.api.letsencrypt.org/directory"
  account_key_pem           = "${tls_private_key.private_key.private_key_pem}"
  common_name               = "example.com"
  subject_alternative_names = ["s3.example.com"]

  dns_challenge {
    provider = "route53"
    config {
      AWS_ACCESS_KEY_ID     = "${var.aws_access_key}"
      AWS_SECRET_ACCESS_KEY = "${var.aws_secret_key}"
      AWS_DEFAULT_REGION    = "us-east-1"
    }
  }
  registration_url = "${acme_registration.reg.id}"
}

resource "aws_iam_server_certificate" "some_cert" {
  name = "some_cert"
  certificate_body = "${acme_certificate.certificate.certificate_pem}"
  private_key = "${acme_certificate.certificate.private_key_pem}"
}
```

The last bit is the only thing I changed.
