### ISSUE TITLE
top domain is not managed by current aws account

### ISSUE THREAD

**Issue by SydOps** [paybyphone/terraform-provider-acme#10]
If root domain (example.com) is managed by different providers. We manage the subdomain as `dev.example.com` in current aws account. 

But when use the sample to create a new certificate, I got below error: 

```
* acme_certificate.certificate: Errors were encountered creating the certificate:
    abc.dev.example.com: Error presenting token: Failed to determine Route 53 hosted zone ID: Zone example.com. not found in Route 53 for domain _acme-challenge.abc.dev.example.com.
```
So can I define the hosted zone ID directly?

**Comment by vancluever** [comment]
Hi @SydOps, unfortunately there is no way to do this in [lego][1], the library we use for this provider.

[1]: https://github.com/xenolf/lego

However, lego determines the domain from the [FindZoneByFQDN function][2] - this function looks for the first domain in the your domain hierarchy that has SOA records (as subdomains should have, when you delegate a zone to a different set of nameservers, that destination delegation should have its own set of SOA records). If the plugin is reporting the root domain, it means it could not find SOA records in the subdomain. You might want to check your zone in route 53, and if they are lacking SOA records, add them appropriately. I would check your domain for you, but I don't see a real domain in your bug report.

[2]: https://github.com/xenolf/lego/blob/306f5c06fa05115b88975eb9f65546db850705ba/acme/dns_challenge.go#L236

Thanks!

**Comment by vancluever** [comment]
Hi @SydOps, any word on this one?

Let me know - if I don't hear anything by tomorrow I'll close this issue, if it's still outstanding you can comment and I'll re-open.

**Comment by SydOps** [comment]
I review the terraform module `aws_route53_record`, it accepts hosted Zone ID. But in this acme module, it can't. 

Any chance to add this feature?
