### ISSUE TITLE
provider not found, provider is there - v0.92

### ISSUE THREAD

**Issue by alex1x** [paybyphone/terraform-provider-acme#12]
I tried to follow this: https://opencredo.com/letsencrypt-terraform/ 

When using latest version terraform v 0.92 I get this error:

```
Error asking for user input: 2 error(s) occurred:

* module.acme-reg.acme_registration.reg: provider acme couldn't be found
* module.acme-cert.acme_certificate.certificate: provider acme couldn't be found
```

But see:

```
$ terraform-provider-acme 
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

It ended up working with an older version (same used in the blogpost shown). I saw https://github.com/paybyphone/terraform-provider-acme/issues/9 -- wonder if similar update is required again for 0.92?

**Comment by vancluever** [comment]
Hey @alex1x, I can't reproduce this with TF v0.9.2 and the v0.3.0 release of the plugin.

Remember that in addition to having downloaded the plugin, you also need to configure your `.terraformrc`. See the [Plugin Basics][1] page on the official site for more details. Let me know if you still encounter the problem after checking the page and reviewing your `.terraformrc`.

[1]: https://www.terraform.io/docs/plugins/basics.html

Thanks!

**Comment by alex1x** [comment]
Hey, you were right, after configuring this in `.terraformc` it works as expected (I also see now that you clarify this on your README, sorry!); thanks for looking.

**Comment by vancluever** [comment]
No problem, glad you figured it out! :)
