### ISSUE TITLE
acme_registration.registration fails to get https://acme-v01.api.letsencrypt.org/directory

### ISSUE THREAD

**Issue by mugizico** [paybyphone/terraform-provider-acme#14]
I am currently running into this error when I use the ACME terraform plugin
```
2017/05/02 10:15:49 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:    

 acme_registration.registration: get directory at 'https://acme-v01.api.letsencrypt.org/directory': 
  failed to get "https://acme-v01.api.letsencrypt.org/directory": Get https://acme- 
  v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection    
 (Client.Timeout exceeded while awaiting headers)    
2017/05/02 10:15:49 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:    

 acme_registration.registration: get directory at 'https://acme-v01.api.letsencrypt.org/directory':       
   failed to get "https://acme-v01.api.letsencrypt.org/directory": Get https://acme- 
  v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection  
  (Client.Timeout exceeded while awaiting headers)   
Error applying plan:   

1 error(s) occurred:   

* acme_registration.registration: get directory at 'https://acme-v01.api.letsencrypt.org/directory':    failed to get "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-     
  v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection    (Client.Timeout exceeded while awaiting headers)    
```

this is what I get when I curl 
```
 curl https://acme-v01.api.letsencrypt.org/directory
{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}% 
```
The plugin seems to be working for other people in the same cidr block. 
I am using v0.2.1 with Terraform 0.8.8

**Comment by vancluever** [comment]
Hi @mugizico, thanks for the report!

Looking at the `lego`'s [http.go](https://github.com/xenolf/lego/blob/a111d61d85454f5d58a0f843ced3413b5678f244/acme/http.go#L18), it looks like the `Timeout` on HTTP connections are 10 seconds, which isn't that short but not really that long either. Just wondering - was there possibly some sort of congestion that you were experiencing on your end when you were experiencing this problem? Did your `curl` succeed right away or was there any sort of significant delay?

Let me know and let me know if the issues are still persisting for you - if they are can you send along the config you are using as well?

Thanks!

**Comment by mugizico** [comment]
Hi @vancluever I've made some progress. This seems to be only a problem when I was my home Wi-Fi. I am thinking that maybe my ISP was blocking those calls to `https://acme-v01.api.letsencrypt.org/directory`(strange that I could still open Chrome/Curl this URL) .  there wasnt any noticeable lag when I `curl`, it succeeded right away

**Comment by vancluever** [comment]
Hey @mugizico, just closing this now as there hasn't been any activity and it looks like it was possibly something locally related. Feel free to open another issue if you have any other problems!
