### ISSUE TITLE
not compatible with terraform 0.8

### ISSUE THREAD

**Issue by hd-deman** [paybyphone/terraform-provider-acme#5]
```
❯ terraform plan
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 1, Ours: 2
```

**Comment by vancluever** [comment]
Thanks for the report @hd-deman, will rebuild tonight!

**Comment by vancluever** [comment]
Hey @hd-deman, happy to say that [`v0.2.0`](https://github.com/paybyphone/terraform-provider-acme/releases/tag/v0.2.0) is out and ready for download! I personally did a test run of this myself on v0.8.0 and all went smooth as far as I can see - but let me know if you have any issues!

This release also includes the ability to do OCSP Stapling too - check the release notes and the `README.md` for more info!

**Comment by hd-deman** [comment]
Thanks a lot.
