### ISSUE TITLE
DNS Challenge does not disable HTTPS server

### ISSUE THREAD

**Issue by nickithewatt** [paybyphone/terraform-provider-acme#6]
Hi,

Unless I am doing something wrong (please do correct me if I am) I am trying to configure my setup  to do a DNS challenge, however I get an error when I run it saying that it can't start an HTTP/S server which I believe should not be the case, and should instead be disabled?

This is the error I am getting:
```
Error applying plan:

1 error(s) occurred:

* acme_certificate.certificate: Errors were encountered creating the certificate:
    example.com: [example.com] error presenting token: Could not start HTTP server for challenge -> listen tcp :80: bind: permission denied
    test.example.com: [test.example.com] error presenting token: Could not start HTTPS server for challenge -> listen tcp :443: bind: permission denied

```

This is what my terraform certificate resource looks like:
```
# Create a certificate
resource "acme_certificate" "certificate" {
  server_url                = "https://acme-staging.api.letsencrypt.org/directory"
  account_key_pem           = "${data.terraform_remote_state.letsencrypt_registration.letsencrypt-registration-privkey}"
    common_name               = "example.com"
  subject_alternative_names = ["test.example.com"]


  dns_challenge {
    provider = "dnsimple"
  }

  registration_url = "${data.terraform_remote_state.letsencrypt_registration.letsencrypt-registration-id}"
}
```

So not sure if this is a bug, or I have done something else wrong?
Thanks!

**Comment by vancluever** [comment]
Hey @nickithewatt, this is odd, because the HTTP/HTTPS servers are designed to not start at all when `dns_challenge` is specified (only one or the other is supported, not both) I'll take a look and try and reproduce over here in the next couple of days!

**Comment by vancluever** [comment]
OK, I'm able to reproduce, for some reason selecting your provider as `dnsimple` breaks this, investigating further.

**Comment by vancluever** [comment]
'twas a very, very silly error. :) Should have this up shortly.

New error output, which is much better :)

```
Error applying plan:

1 error(s) occurred:

* acme_certificate.certificate: DNSimple credentials missing
```

**Comment by vancluever** [comment]
Hey @nickithewatt, v0.2.1 is now up, can you check and see if this fixes it for you or makes the nature of the error more clear?

Remember that you need to either supply your provider credentials and/or configuration either in the TF config or via environment variables. Remember to look at the [lego project's DNS challenge provider directory][1] for the instructions specific to the provider you want to use.

[1]: https://github.com/xenolf/lego/tree/master/providers/dns

For DNSimple, for example, looks like you want for settings:

```
// Credentials must be passed in the environment variables: DNSIMPLE_EMAIL
// and DNSIMPLE_API_KEY.
```

You don't necessarily need to do this with env vars, remember - you can also do the following, adjusted for security and comfort levels:

```
dns_challenge {
  provider = "dnsimple"
  config {
    DNSIMPLE_EMAIL   = "nobody@example.com"
    DNSIMPLE_API_KEY = "API_KEY_HERE"
  }
}
```

Thanks!

**Comment by nickithewatt** [comment]
Thanks @vancluever I will test v0.2.1 out and let you know. 
For my previous attempts I believe I was using environment variables but I will double check (As part of my overall Terraform config I was also creating dnsimple records which it did manage to create successfully). In any case, thanks for the update, I shall test it out and let you know!

**Comment by nickithewatt** [comment]
@vancluever thanks, all is well again! 

With v0.2.1 I do now also get the `* acme_certificate.certificate: DNSimple credentials missing` error which definitely helped to shed more light on my original underlying problem thanks! 
It turns out that the environment variable names used by Lego, and those by Terraform are almost the same, but not quite, which is why I had my original error - so there was a bit of my bad in there as well!

For Terraform the environment variables are:
```
    DNSIMPLE_EMAIL = "nobody@example.com"
    DNSIMPLE_TOKEN = "API_KEY_HERE"
```
whilst for Lego the environment variables are:
```
    DNSIMPLE_EMAIL   = "nobody@example.com"
    DNSIMPLE_API_KEY = "API_KEY_HERE"
```
So with your changes, and my fixes to environment variables, all is well! Thank you very much!

**Comment by vancluever** [comment]
Excellent @nickithewatt! Thanks for confirming that the issue is fixed for you. Too bad about the config discrepancy (looks like lego and TF use different 3rd party SDKs for DNSimple) but looks like you got it sorted now - glad it all worked out!
