### ISSUE TITLE
Incompatible API version with plugin error

### ISSUE THREAD

**Issue by zot24** [paybyphone/terraform-provider-acme#7]
I'm using:

Terraform v0.8.6 and have tried as well Terraform v0.8.0 however I'm getting the following error:

```
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 3, Ours: 2
``` 

The last bit it's confusing `version: 3, Ours: 2` ? sound's like the plugin version it's newer than the version on my local Terraform the opposite of what's going on in this closed issue https://github.com/paybyphone/terraform-provider-acme/issues/5

Any idea why this could be happening?

btw I used brew to install go and I'm on mac (El Capitan)

Thanks,

**Comment by vancluever** [comment]
Hey @zot24, sorry you are having this issue! I don't have an El Capitan box to test this on but I can't reproduce this on my Linux box using latest TF and version of the plugin (v0.2.1) - will check on one of my Sierra machines though. 

Do you have any other plugins installed as well?

**Comment by vancluever** [comment]
Hey @zot24, just tried on Sierra, the run succeeded (no errors).

At this point I'm kind of wondering if you have any other plugins installed that may be building against a new version of the plugin API (ie: if maybe 0.9 is bumping the API version again)?

Let me know - sorry I could not reproduce it over here!

**Comment by zot24** [comment]
np @vancluever! I don't have any other plugins this is the first one I trying to install I might be doing something wrong tho... I'll try to re do the whole process again and report back, thanks

**Comment by zot24** [comment]
This is more or less the process I follow to install the plugin, just in case you spot something wrong:

- brew install go
- add to ~/.zshrc the following:

```
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin
```

- go get -u github.com/hashicorp/terraform/plugin
- go get -u github.com/paybyphone/terraform-provider-acme/plugin/providers/acme
- make build
- add to ~/.terraformrc the following:

```
providers {
    acme = "~/Desktop/terraform-provider-acme/pkg/darwin_amd64/terraform-provider-acme"
}
```

**Comment by vancluever** [comment]
Hey @zot24 ahh! Yeah that might be your issue - sounds like TF might be gearing up for an API version bump (`go get -u github.com/hashicorp/terraform/plugin` would pull from the TF master)

What I would recommend instead is grabbing the latest built binary version of the plugin from [the releases page][1]. These are signed too if you want extra assurance (I make SHA256 hashes and sign the sums file just like HashiCorp does for TF). 

[1]: https://github.com/paybyphone/terraform-provider-acme/releases

Drop it somewhere like `$HOME/bin` and add that as the path to the plugin in `.terraformrc`.

Barring that, if you want to build from source, `github.com/hashicorp/terraform/plugin` has been vendored in the repo, so you can skip `go get -u github.com/hashicorp/terraform/plugin` and just use the repo directly. YMMV though as I don't use `go build .` as part of the toolchain directly (I use `gox` to cross-compile), but it sounds like it's building successfully.

**Comment by zot24** [comment]
Thanks you so much @vancluever that looks like the problem I'm having 👍

**Comment by vancluever** [comment]
Glad that fixed it for you @zot24!
