### ISSUE TITLE
Current Release Doesn't work with terraform v0.9.0

### ISSUE THREAD

**Issue by bobbydeveaux** [paybyphone/terraform-provider-acme#9]
I had to download and `make build` to allow this to work with the latest version of terraform due to plugin version error (2 => 3). Didn't have to edit any code, just re-built.

Cheers

**Comment by vancluever** [comment]
Hey @bobbydeveaux - Will rebuild soon with the latest TF! Thanks for letting me know!

**Comment by bobbydeveaux** [comment]
No worries :)

**Comment by vancluever** [comment]
Hey @bobbydeveaux, `v0.3.0-beta1` is ready, tagged as beta just to note that v0.9.0 is not fully released yet. In any case, current S3 outages in progress are keeping me from uploading the release, but once those have passed I will put up the binaries!

If you are impatient however, running `make build` against the `v0.3.0-beta1` branch should give you the binaries you need.

Cheers!

**Comment by bobbydeveaux** [comment]
awesome - these are my favourite AWS Outage tweets, "
1 ) https://twitter.com/bcbwilla/status/836669511231127552
2) "AWS going down is basically the software developer's equivalent of a Snow Day."

Thanks again! :D

**Comment by vancluever** [comment]
No sweat @bobbydeveaux! 

The release is uploaded now, but incremented to `beta2` due to a false start with S3 earlier on.

In any case, give it a shot and let me know how it goes!

[Link](https://github.com/paybyphone/terraform-provider-acme/releases/tag/v0.3.0-beta2)

**Comment by vancluever** [comment]
Hey @bobbydeveaux have you had a chance to give the new binary a try? Let me know!

Just want to confirm before I close this ticket.

Thanks!

**Comment by vancluever** [comment]
Closing this down now - assuming everything is working okay here. Will be releasing full when TF 0.9.0 comes out but otherwise let me know if there are any issues!
